### ISSUE TITLE
Which controller use MPC?

### ISSUE THREAD

**Issue by Zhouxiang1027** [amilearning/PX4_Firmware_rw#1]

**Comment by amilearning** [comment]
I apologize for any confusion caused by the repository description. This PX4 firmware is used solely for our off-road platform, which uses MPC as its controller. We have not implemented any MPC within this PX4 firmware repository.


Hojin Lee

School of Mechanical, Aerospace and Nuclear Engineering

Ulsan National Institute of Science and Technology (UNIST)

Ulsan, Republic of Korea

Mobile: +82)(0)10-8590-2107


________________________________
From: Zhouxiang ***@***.***>
Sent: 27 June 2024 00:17
To: amilearning/PX4_Firmware_rw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amilearning/PX4_Firmware_rw] Which controller use MPC? (Issue #1)

**Comment by Zhouxiang1027** [comment]
thanks for your answer



周翔


------------------ Original ------------------
From: HO JIN LEE ***@***.***&gt;
Date: Wed,Jun 26,2024 11:22 PM
To: amilearning/PX4_Firmware_rw ***@***.***&gt;
Cc: Zhouxiang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [amilearning/PX4_Firmware_rw] Which controller use MPC? (Issue#1)





 I apologize for any confusion caused by the repository description. This PX4 firmware is used solely for our off-road platform, which uses MPC as its controller. We have not implemented any MPC within this PX4 firmware repository. 
 
 
 Hojin Lee 
 
 School of Mechanical, Aerospace and Nuclear Engineering 
 
 Ulsan National Institute of Science and Technology (UNIST) 
 
 Ulsan, Republic of Korea 
 
 Mobile: +82)(0)10-8590-2107 
 
 
 ________________________________ 
 From: Zhouxiang ***@***.***&gt; 
 Sent: 27 June 2024 00:17 
 To: amilearning/PX4_Firmware_rw ***@***.***&gt; 
 Cc: Subscribed ***@***.***&gt; 
 Subject: [amilearning/PX4_Firmware_rw] Which controller use MPC? (Issue #1)
